sudo: false

language: node_js
node_js: '10'
os:
  - osx
  - linux
  - windows

dist: xenial
services:
  xvfb

install:
  - npm install

script:
  - npm test --silent

matrix:
  allow_failures:
    - os: windows
